CREATE TABLE TIMES_SERIE_A (
    ID NUMBER(8) NOT NULL,
    NOME VARCHAR2(60) NOT NULL,
    CONSTRAINT TIMES_SERIE_A_PK PRIMARY KEY (ID)
    ENABLE
);

CREATE SEQUENCE SEQ_TIMES_SERIE_A  
    MINVALUE 1 
    MAXVALUE 999999999999999999999999999 
    INCREMENT BY 1 
    START WITH 1 
    CACHE 20 
    NOORDER  
    NOCYCLE;

INSERT INTO TIMES_SERIE_A (ID, NOME) VALUES (SEQ_TIMES_SERIE_A.NEXTVAL, 'CORINTHIANS');
INSERT INTO TIMES_SERIE_A (ID, NOME) VALUES (SEQ_TIMES_SERIE_A.NEXTVAL, 'GRÊMIO');
INSERT INTO TIMES_SERIE_A (ID, NOME) VALUES (SEQ_TIMES_SERIE_A.NEXTVAL, 'SANTOS');
INSERT INTO TIMES_SERIE_A (ID, NOME) VALUES (SEQ_TIMES_SERIE_A.NEXTVAL, 'BOTAFOGO');
INSERT INTO TIMES_SERIE_A (ID, NOME) VALUES (SEQ_TIMES_SERIE_A.NEXTVAL, 'CORITIBA');
INSERT INTO TIMES_SERIE_A (ID, NOME) VALUES (SEQ_TIMES_SERIE_A.NEXTVAL, 'FLUMINENSE');
INSERT INTO TIMES_SERIE_A (ID, NOME) VALUES (SEQ_TIMES_SERIE_A.NEXTVAL, 'PONTE PRETA');
INSERT INTO TIMES_SERIE_A (ID, NOME) VALUES (SEQ_TIMES_SERIE_A.NEXTVAL, 'FLAMENGO');
INSERT INTO TIMES_SERIE_A (ID, NOME) VALUES (SEQ_TIMES_SERIE_A.NEXTVAL, 'PALMEIRAS');
INSERT INTO TIMES_SERIE_A (ID, NOME) VALUES (SEQ_TIMES_SERIE_A.NEXTVAL, 'CHAPECOENSE');
INSERT INTO TIMES_SERIE_A (ID, NOME) VALUES (SEQ_TIMES_SERIE_A.NEXTVAL, 'VASCO');
INSERT INTO TIMES_SERIE_A (ID, NOME) VALUES (SEQ_TIMES_SERIE_A.NEXTVAL, 'CRUZEIRO');
INSERT INTO TIMES_SERIE_A (ID, NOME) VALUES (SEQ_TIMES_SERIE_A.NEXTVAL, 'ATLÉTICO-PR');
INSERT INTO TIMES_SERIE_A (ID, NOME) VALUES (SEQ_TIMES_SERIE_A.NEXTVAL, 'SÃO PAULO');
INSERT INTO TIMES_SERIE_A (ID, NOME) VALUES (SEQ_TIMES_SERIE_A.NEXTVAL, 'BAHIA');
INSERT INTO TIMES_SERIE_A (ID, NOME) VALUES (SEQ_TIMES_SERIE_A.NEXTVAL, 'ATLÉTICO-MG');
INSERT INTO TIMES_SERIE_A (ID, NOME) VALUES (SEQ_TIMES_SERIE_A.NEXTVAL, 'SPORT');
INSERT INTO TIMES_SERIE_A (ID, NOME) VALUES (SEQ_TIMES_SERIE_A.NEXTVAL, 'VITÓRIA');
INSERT INTO TIMES_SERIE_A (ID, NOME) VALUES (SEQ_TIMES_SERIE_A.NEXTVAL, 'ATLÉTICO-GO');
INSERT INTO TIMES_SERIE_A (ID, NOME) VALUES (SEQ_TIMES_SERIE_A.NEXTVAL, 'AVAÍ');
